export type BillingStatus = "unpaid" | "partial" | "paid" | "overpaid" | "closed";

export type PlanCurrency = "SYP" | "USD" | "EUR" | "TRY" | string;

export interface Subscription {
  id: string;
  userId: string;
  planKey: string;
  planName: string;
  currency: PlanCurrency;
  startDate: string;
  endDate: string;
  cycleIndex: number;
  previousCycleId: string | null;
  nextCycleId: string | null;
  expectedAmount: number;
  amountPaid: number;
  carryIn: number;
  carryOut: number;
  status: BillingStatus;
  paymentStatus: BillingStatus;
  autoGenerated: boolean;
  createdAt: string;
}

export interface Payment {
  id: string;
  subId: string;
  paymentDate: string;
  amount: number;
  currency: PlanCurrency;
  method: string;
  note: string;
  createdBy: string;
  createdAt: string;
}

export interface BillingSummary {
  userId: string;
  activeSubscriptionId: string | null;
  walletBalance: number;
  totalExpected: number;
  totalPaid: number;
  totalRemaining: number;
  cycleCount: number;
  currentCycle: Subscription | null;
  lastUpdatedAt?: string;
}

export interface BillingSummaryRow {
  userId: string;
  fullname: string;
  username: string;
  walletBalance: number;
  totalExpected: number;
  totalPaid: number;
  cycles: Subscription[];
}
